apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      containers:
      - name: apmongo
        image: mongo
        ports:
          - containerPort: 27017
---        
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
     app: mongo
     tier: backend
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
