apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-depoy   #deployment name
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: 
        image: alpine
        ports:
          - containerPort: 3030
