apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
     app: webapps
  ports:
    - name: http
      port: 80
      targetPort: 7000
      nodePort: 32000

  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    app: webapps
spec:
  containers:
  - name: pod1
    image: httpd
